import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../core/config/app_theme.dart';
import '../../core/state/workspace_controller.dart';

class SystemAlertsPage extends StatefulWidget { const SystemAlertsPage({super.key}); @override State<SystemAlertsPage> createState()=>_SystemAlertsPageState(); }
class _SystemAlertsPageState extends State<SystemAlertsPage>{ late Future<Map<String,dynamic>> _future; @override void initState(){super.initState();_future=_load();} Future<Map<String,dynamic>> _load(){final w=context.read<WorkspaceController>();return w.storeApi.systemAlerts(w.activeStoreToken!);} void _refresh(){final next=_load();setState((){_future=next;});}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('System & Plan Alerts'),actions:[IconButton(onPressed:_refresh,icon:const Icon(Icons.refresh))]),body:FutureBuilder<Map<String,dynamic>>(future:_future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator()); if(s.hasError)return Center(child:Text(s.error.toString())); final rows=((s.data?['data']??[]) as List<dynamic>).cast<Map<String,dynamic>>(); if(rows.isEmpty)return const Center(child:Text('No system alerts.')); return ListView.builder(padding:const EdgeInsets.all(12),itemCount:rows.length,itemBuilder:(context,i){final a=rows[i];final level=a['level']?.toString()??'info';final icon=level=='danger'?Icons.error_outline:level=='warning'?Icons.warning_amber_outlined:Icons.info_outline;return Card(child:ListTile(leading:Icon(icon,color:level=='danger'?Colors.red:level=='warning'?Colors.orange:AppTheme.primary),title:Text(a['title']?.toString()??'Alert',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text(a['message']?.toString()??'')));});})); }
