import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../core/state/workspace_controller.dart';

class WarehousesPage extends StatefulWidget { const WarehousesPage({super.key}); @override State<WarehousesPage> createState()=>_WarehousesPageState(); }
class _WarehousesPageState extends State<WarehousesPage>{ late Future<Map<String,dynamic>> _future; @override void initState(){super.initState();_future=_load();} Future<Map<String,dynamic>> _load()=>context.read<WorkspaceController>().storeApi.warehouses(context.read<WorkspaceController>().activeStoreToken!); void _refresh(){final f=_load();setState((){_future=f;});}
Future<void> _form([Map<String,dynamic>? w]) async{final name=TextEditingController(text:w?['name']?.toString()??'');final code=TextEditingController(text:w?['code']?.toString()??'');final address=TextEditingController(text:w?['address']?.toString()??'');bool def=w?['is_default']==true;bool active=w?['status']!=false;final ok=await showDialog<bool>(context:context,builder:(context)=>StatefulBuilder(builder:(context,setLocal)=>AlertDialog(title:Text(w==null?'Add Warehouse':'Edit Warehouse'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Name')),const SizedBox(height:8),TextField(controller:code,decoration:const InputDecoration(labelText:'Code')),const SizedBox(height:8),TextField(controller:address,decoration:const InputDecoration(labelText:'Address')),SwitchListTile(value:def,onChanged:(v)=>setLocal(()=>def=v),title:const Text('Default warehouse')),SwitchListTile(value:active,onChanged:(v)=>setLocal(()=>active=v),title:const Text('Active'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Save'))]))); if(ok!=true)return; try{final api=context.read<WorkspaceController>().storeApi;final token=context.read<WorkspaceController>().activeStoreToken!;final data={'name':name.text.trim(),'code':code.text.trim(),'address':address.text.trim(),'is_default':def,'status':active}; if(w==null){await api.createWarehouse(token,data);}else{await api.updateWarehouse(token,int.parse(w['id'].toString()),data);} _refresh();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
Future<void> _delete(Map<String,dynamic> w)async{try{await context.read<WorkspaceController>().storeApi.deleteWarehouse(context.read<WorkspaceController>().activeStoreToken!,int.parse(w['id'].toString()));_refresh();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Warehouses'),actions:[IconButton(onPressed:_refresh,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>_form(),icon:const Icon(Icons.add),label:const Text('Warehouse')),body:FutureBuilder<Map<String,dynamic>>(future:_future,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator()); if(s.hasError)return Center(child:Text(s.error.toString())); final rows=(s.data?['data'] as List<dynamic>? ?? []).cast<Map<String,dynamic>>(); if(rows.isEmpty)return const Center(child:Text('No warehouse found.')); return ListView.builder(padding:const EdgeInsets.all(12),itemCount:rows.length,itemBuilder:(context,i){final w=rows[i];return Card(child:ListTile(title:Text('${w['name']} ${w['is_default']==true?'• Default':''}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${w['code']??''}\n${w['address']??''}'),isThreeLine:true,trailing:PopupMenuButton<String>(onSelected:(v){if(v=='edit')_form(w); if(v=='delete')_delete(w);},itemBuilder:(_)=>const [PopupMenuItem(value:'edit',child:Text('Edit')),PopupMenuItem(value:'delete',child:Text('Delete'))]),onTap:()=>_form(w)));});}));}
